kind: PersistentVolume
apiVersion: v1
metadata:
  name: logging-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: logging
spec:
  storageClassName: manual-logging
  capacity:
    storage: 25Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logging-pv-claim  # Sets name of PVC
  labels:
    app: logging
spec:
  storageClassName: manual-logging
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 25Gi  # Sets volume size
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  labels:
    app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Parsers_File  parsers.conf
        Log_Level     info
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5M
        Skip_Long_Lines   On
        Refresh_Interval  10
    [FILTER]
        Name parser
        Match **
        Parser any
        Key_Name log
    [OUTPUT]
        Name file
        Match *
        Path /data
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Decode_Field_As   escaped    log
    [PARSER]
        Name        any
        Format      regex
        Regex       ^(?<log>.*)$
        Time_Key    time
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd-logger
spec:
  selector:
    matchLabels:
      app: fluentd-logger
  template:
    metadata:
      labels:
        app: fluentd-logger
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: fluent-bit
        image: amazon/aws-for-fluent-bit:latest
        # env:
        # - name:  FLUENT_ELASTICSEARCH_HOST
        #   value: "elasticsearch-master"
        # - name:  FLUENT_ELASTICSEARCH_PORT
        #   value: "9200"
        # - name: FLUENT_ELASTICSEARCH_SCHEME
        #   value: "http" # Either HTTP or HTTPS.
        # - name: FLUENT_ELASTICSEARCH_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: elasticsearch-master-credentials
        #       key: username
        # - name: FLUENT_ELASTICSEARCH_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: elasticsearch-master-credentials
        #       key: password
        # - name: FLUENTD_SYSTEMD_CONF
        #   value: disable
        # - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
        #   value: /var/log/containers/fluent*
        # - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
        #   value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/ 
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: dockerlogs
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: persistent-storage
          mountPath: /data
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 100Mi
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: dockerlogs
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: logging-pv-claim