# TODO: complete me
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aggregator
            image: hw2-aggregator:v1
          restartPolicy: Never
