kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-storage
provisioner: efs.csi.aws.com
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-pv-volume  # Sets PV's name
  labels:
    app: storage
spec:
  storageClassName: efs-storage
  capacity:
    storage: 5Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0f384963e00a7170a::fsap-0a0253128b63742f6
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-pv-claim  # Sets name of PVC
  labels:
    app: storage
spec:
  storageClassName: efs-storage
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 5Gi  # Sets volume size