apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
      - name: ghcr-registry-secret
      containers:
      - name: web
        image: ghcr.io/dhruvshah1214/cis188fp-web:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: POSTGRES_HOST_URL
          value: "postgres:5432"
        - name: POSTGRES_DB_NAME
          value: "postgres"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: ADMIN_RESTRICTED
          value: "true"
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: web-admin-secret
              key: username
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: web-admin-secret
              key: password
        - name: BCRYPT_LOG_ROUNDS
          value: "10"
        volumeMounts:
          - name: config-vol
            mountPath: /app/config/
      volumes:
      - name: config-vol
        configMap:
          name: config-map
          items:
            - key: allowed-monitors
              path: allowedmonitors
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8000
